In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import joblib

In [2]:
sonar_data = pd.read_csv('/content/Sonar data.csv', header = None)
sonar_data

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0090  0.0032   R  
1    0.0052  0.0044   R  
2    0.0095  0.0078   R  
3    0.0040  0.0117   R  
4    0.0107  0.0094   R  
..      ...     ...  ..  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[208 rows x 61 columns]

In [3]:
x = sonar_data.drop(columns = 60, axis = 1)
y = sonar_data[60]

In [4]:
le = LabelEncoder()
y_le = le.fit_transform(y)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y_le, test_size = 0.3)

In [6]:
model = LogisticRegression()

In [7]:
model.fit(x_train, y_train)

LogisticRegression()

In [8]:
input =  (0.0192,	0.0607,	0.0378,	0.0774,	0.1388,	0.0809,	0.0568,	0.0219,	0.1037,	0.1186,	0.1237,	0.1601,	0.352,	0.4479,	0.3769,	0.5761,	0.6426,	0.679,	0.7157,	0.5466,	0.5399,	0.6362,	0.7849,	0.7756,	0.578,	0.4862,	0.4181,	0.2457,	0.0716,	0.0613,	0.1816,	0.4493,	0.5976,	0.3785,	0.2495,	0.5771,	0.8852,	0.8409,	0.357,	0.3133,	0.6096,	0.6378,	0.2709,	0.1419,	0.126,	0.1288,	0.079,	0.0829,	0.052,	0.0216,	0.036	,0.0331,	0.0131,	0.012,	0.0108,	0.0024,	0.0045,	0.0037,	0.0112,	0.0075)
input_reshaped = np.asarray(input).reshape(1, -1)
model.predict(input_reshaped)

array([0])

In [9]:
if model.predict(input_reshaped) == 1:
  print("It is a Rock")
else:
  print("It is a mine")

It is a mine


In [10]:
model.predict(x_test)

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

In [11]:
model.score(x_test, y_test)

0.8253968253968254

In [15]:
joblib.dump(model, 'model.joblib')
mj = joblib.load('model.joblib')


In [13]:
mj.predict(x_test)

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

In [14]:
mj.score(x_test, y_test)

0.8253968253968254